package com.ih.osm.designsystem.theme

import androidx.compose.ui.graphics.Color

val OsmGreen = Color(0xFF3B8D2F)

internal val LightPrimary = OsmGreen
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFDDF4D8)
internal val LightOnPrimaryContainer = Color(0xFF123A15)
internal val LightSecondary = Color(0xFF52634F)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFD5E8D1)
internal val LightOnSecondaryContainer = Color(0xFF101F10)
internal val LightBackground = Color(0xFFF8FAF7)
internal val LightOnBackground = Color(0xFF191C18)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightOnSurface = Color(0xFF191C18)
internal val LightSurfaceVariant = Color(0xFFF0F2EE)
internal val LightOnSurfaceVariant = Color(0xFF444842)
internal val LightOutline = Color(0xFF747970)
internal val LightOutlineVariant = Color(0xFFE1E4DE)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)

internal val DarkPrimary = Color(0xFF82D477)
internal val DarkOnPrimary = Color(0xFF0C3A10)
internal val DarkPrimaryContainer = Color(0xFF245D28)
internal val DarkOnPrimaryContainer = Color(0xFFDDF4D8)
internal val DarkSecondary = Color(0xFFB8CCB4)
internal val DarkOnSecondary = Color(0xFF243523)
internal val DarkSecondaryContainer = Color(0xFF3A4B38)
internal val DarkOnSecondaryContainer = Color(0xFFD5E8D1)
internal val DarkBackground = Color(0xFF101410)
internal val DarkOnBackground = Color(0xFFE1E4DE)
internal val DarkSurface = Color(0xFF181C18)
internal val DarkOnSurface = Color(0xFFE1E4DE)
internal val DarkSurfaceVariant = Color(0xFF232823)
internal val DarkOnSurfaceVariant = Color(0xFFC4C8C0)
internal val DarkOutline = Color(0xFF8E938A)
internal val DarkOutlineVariant = Color(0xFF414740)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
