import Foundation

enum AppStrings {
    enum Accessibility {
        static let dismiss: LocalizedStringResource = "accessibility.dismiss"
        static let hidePassword: LocalizedStringResource = "accessibility.password.hide"
        static let showPassword: LocalizedStringResource = "accessibility.password.show"
        static let loading: LocalizedStringResource = "accessibility.loading"
        static let bannerError: LocalizedStringResource = "accessibility.banner.error"
        static let bannerWarning: LocalizedStringResource = "accessibility.banner.warning"
        static let bannerInfo: LocalizedStringResource = "accessibility.banner.info"
        static let bannerSuccess: LocalizedStringResource = "accessibility.banner.success"
    }

    enum Login {
        static let brandName: LocalizedStringResource = "login.brand.name"
        static let brandTagline: LocalizedStringResource = "login.brand.tagline"
        static let title: LocalizedStringResource = "login.title"
        static let subtitle: LocalizedStringResource = "login.subtitle"
        static let emailLabel: LocalizedStringResource = "login.email.label"
        static let emailPlaceholder: LocalizedStringResource = "login.email.placeholder"
        static let passwordLabel: LocalizedStringResource = "login.password.label"
        static let passwordPlaceholder: LocalizedStringResource = "login.password.placeholder"
        static let emailRequired: LocalizedStringResource = "login.email.error.required"
        static let emailInvalid: LocalizedStringResource = "login.email.error.invalid"
        static let passwordRequired: LocalizedStringResource = "login.password.error.required"
        static let passwordTooShort: LocalizedStringResource = "login.password.error.too_short"
        static let forgotPassword: LocalizedStringResource = "login.forgot_password"
        static let submit: LocalizedStringResource = "login.submit"
        static let secureAccess: LocalizedStringResource = "login.secure_access"
        static let genericError: LocalizedStringResource = "login.error.generic"
    }

    enum Session {
        static let loading: LocalizedStringResource = "session.loading"
    }

    enum Home {
        static let greeting: LocalizedStringResource = "home.greeting"
        static let quickActions: LocalizedStringResource = "home.quick_actions"
        static let newNote: LocalizedStringResource = "home.action.new_note"
        static let scanQR: LocalizedStringResource = "home.action.scan_qr"
        static let fastPassword: LocalizedStringResource = "home.action.fast_password"
        static let notes: LocalizedStringResource = "home.action.notes"
        static let pendingCardsTitle: LocalizedStringResource = "home.pending_cards.title"
        static let pendingCardsBody: LocalizedStringResource = "home.pending_cards.body"
        static let pendingCardsAction: LocalizedStringResource = "home.pending_cards.action"
    }

    enum Permissions {
        static let title: LocalizedStringResource = "permissions.title"
        static let subtitle: LocalizedStringResource = "permissions.subtitle"
        static let continueAction: LocalizedStringResource = "permissions.continue"
        static let openSettings: LocalizedStringResource = "permissions.open_settings"
        static let notNow: LocalizedStringResource = "permissions.not_now"
        static let notificationsTitle: LocalizedStringResource = "permissions.notifications.title"
        static let notificationsDescription: LocalizedStringResource = "permissions.notifications.description"
        static let cameraTitle: LocalizedStringResource = "permissions.camera.title"
        static let cameraDescription: LocalizedStringResource = "permissions.camera.description"
        static let microphoneTitle: LocalizedStringResource = "permissions.microphone.title"
        static let microphoneDescription: LocalizedStringResource = "permissions.microphone.description"
        static let galleryTitle: LocalizedStringResource = "permissions.gallery.title"
        static let galleryDescription: LocalizedStringResource = "permissions.gallery.description"
        static let backgroundTitle: LocalizedStringResource = "permissions.background.title"
        static let backgroundDescription: LocalizedStringResource = "permissions.background.description"
        static let granted: LocalizedStringResource = "permissions.status.granted"
        static let partial: LocalizedStringResource = "permissions.status.partial"
        static let pending: LocalizedStringResource = "permissions.status.pending"
        static let denied: LocalizedStringResource = "permissions.status.denied"
        static let ready: LocalizedStringResource = "permissions.status.ready"
    }

    enum CatalogSync {
        static let title: LocalizedStringResource = "catalog_sync.title"
        static let starting: LocalizedStringResource = "catalog_sync.starting"
        static let waiting: LocalizedStringResource = "catalog_sync.waiting"
        static let failed: LocalizedStringResource = "catalog_sync.failed"
        static let genericError: LocalizedStringResource = "catalog_sync.error.generic"
        static let cardTypes: LocalizedStringResource = "catalog_sync.card_types"
        static let preclassifiers: LocalizedStringResource = "catalog_sync.preclassifiers"
        static let priorities: LocalizedStringResource = "catalog_sync.priorities"
        static let levels: LocalizedStringResource = "catalog_sync.levels"
        static let employees: LocalizedStringResource = "catalog_sync.employees"
    }

    enum Network {
        static let wifiConnected: LocalizedStringResource = "network.wifi.connected"
        static let wifiNoInternet: LocalizedStringResource = "network.wifi.no_internet"
        static let mobileConnected: LocalizedStringResource = "network.mobile.connected"
        static let mobileNoInternet: LocalizedStringResource = "network.mobile.no_internet"
        static let offline: LocalizedStringResource = "network.offline"
    }

    enum Navigation {
        static let home: LocalizedStringResource = "navigation.home"
        static let notes: LocalizedStringResource = "navigation.notes"
        static let cards: LocalizedStringResource = "navigation.cards"
        static let settings: LocalizedStringResource = "navigation.settings"
    }

    enum Common {
        static let cancel: LocalizedStringResource = "common.cancel"
        static let done: LocalizedStringResource = "common.done"
    }

    enum Cards {
        static let title: LocalizedStringResource = "cards.title"
        static let count: LocalizedStringResource = "cards.count"
        static let searchPrompt: LocalizedStringResource = "cards.search_prompt"
        static let active: LocalizedStringResource = "cards.filter.active"
        static let custom: LocalizedStringResource = "cards.filter.custom"
        static let assigned: LocalizedStringResource = "cards.filter.assigned"
        static let overdue: LocalizedStringResource = "cards.filter.overdue"
        static let filters: LocalizedStringResource = "cards.filters"
        static let filtersSubtitle: LocalizedStringResource = "cards.filters.subtitle"
        static let allOpen: LocalizedStringResource = "cards.filter.all_open"
        static let myOpen: LocalizedStringResource = "cards.filter.my_open"
        static let myAssigned: LocalizedStringResource = "cards.filter.my_assigned"
        static let unassignedCards: LocalizedStringResource = "cards.filter.unassigned"
        static let dueCards: LocalizedStringResource = "cards.filter.due"
        static let closedCards: LocalizedStringResource = "cards.filter.closed"
        static let clearFilters: LocalizedStringResource = "cards.filter.clear"
        static let refresh: LocalizedStringResource = "cards.refresh"
        static let retry: LocalizedStringResource = "cards.retry"
        static let create: LocalizedStringResource = "cards.create"
        static let localFolio: LocalizedStringResource = "cards.local_folio"
        static let unknownType: LocalizedStringResource = "cards.unknown_type"
        static let noDescription: LocalizedStringResource = "cards.no_description"
        static let statusOpen: LocalizedStringResource = "cards.status.open"
        static let statusOverdue: LocalizedStringResource = "cards.status.overdue"
        static let statusClosed: LocalizedStringResource = "cards.status.closed"
        static let pendingSync: LocalizedStringResource = "cards.pending_sync"
        static let localSolution: LocalizedStringResource = "cards.local_solution"
        static let unassigned: LocalizedStringResource = "cards.unassigned"
        static let emptySearch: LocalizedStringResource = "cards.empty.search"
        static let emptyFilter: LocalizedStringResource = "cards.empty.filter"
        static let emptySupport: LocalizedStringResource = "cards.empty.support"
        static let actionsTitle: LocalizedStringResource = "cards.actions.title"
        static let actionsSubtitle: LocalizedStringResource = "cards.actions.subtitle"
        static let provisionalSolution: LocalizedStringResource = "cards.actions.provisional"
        static let definitiveSolution: LocalizedStringResource = "cards.actions.definitive"
    }

    enum CreateCard {
        static let title: LocalizedStringResource = "create_card.title"
        static let back: LocalizedStringResource = "create_card.back"
        static let classificationTitle: LocalizedStringResource = "create_card.classification.title"
        static let classificationSubtitle: LocalizedStringResource = "create_card.classification.subtitle"
        static let typeLabel: LocalizedStringResource = "create_card.type.label"
        static let typePlaceholder: LocalizedStringResource = "create_card.type.placeholder"
        static let conditionLabel: LocalizedStringResource = "create_card.condition.label"
        static let conditionPlaceholder: LocalizedStringResource = "create_card.condition.placeholder"
        static let conditionSafe: LocalizedStringResource = "create_card.condition.safe"
        static let conditionUnsafe: LocalizedStringResource = "create_card.condition.unsafe"
        static let preclassifierLabel: LocalizedStringResource = "create_card.preclassifier.label"
        static let preclassifierPlaceholder: LocalizedStringResource = "create_card.preclassifier.placeholder"
        static let priorityLabel: LocalizedStringResource = "create_card.priority.label"
        static let priorityPlaceholder: LocalizedStringResource = "create_card.priority.placeholder"
        static let dueDateLabel: LocalizedStringResource = "create_card.due_date.label"
        static let dueDatePlaceholder: LocalizedStringResource = "create_card.due_date.placeholder"
        static let locationTitle: LocalizedStringResource = "create_card.location.title"
        static let locationSubtitle: LocalizedStringResource = "create_card.location.subtitle"
        static let levelLabel: LocalizedStringResource = "create_card.level.label"
        static let levelPlaceholder: LocalizedStringResource = "create_card.level.placeholder"
        static let levelHelper: LocalizedStringResource = "create_card.level.helper"
        static let evidenceTitle: LocalizedStringResource = "create_card.evidence.title"
        static let evidenceSubtitle: LocalizedStringResource = "create_card.evidence.subtitle"
        static let photos: LocalizedStringResource = "create_card.evidence.photos"
        static let videos: LocalizedStringResource = "create_card.evidence.videos"
        static let audio: LocalizedStringResource = "create_card.evidence.audio"
        static let attachedEvidence: LocalizedStringResource = "create_card.evidence.attached"
        static let processingEvidence: LocalizedStringResource = "create_card.evidence.processing"
        static let evidenceSource: LocalizedStringResource = "create_card.evidence.source"
        static let camera: LocalizedStringResource = "create_card.evidence.camera"
        static let photoLibrary: LocalizedStringResource = "create_card.evidence.library"
        static let removeEvidence: LocalizedStringResource = "create_card.evidence.remove"
        static let countLimit: LocalizedStringResource = "create_card.evidence.count_limit"
        static let timedCountLimit: LocalizedStringResource = "create_card.evidence.timed_count_limit"
        static let recordAudio: LocalizedStringResource = "create_card.evidence.record_audio"
        static let startRecording: LocalizedStringResource = "create_card.evidence.start_recording"
        static let stopRecording: LocalizedStringResource = "create_card.evidence.stop_recording"
        static let attachRecording: LocalizedStringResource = "create_card.evidence.attach_recording"
        static let audioMaximum: LocalizedStringResource = "create_card.evidence.audio_maximum"
        static let detailsTitle: LocalizedStringResource = "create_card.details.title"
        static let detailsSubtitle: LocalizedStringResource = "create_card.details.subtitle"
        static let descriptionPlaceholder: LocalizedStringResource = "create_card.description.placeholder"
        static let reviewTitle: LocalizedStringResource = "create_card.review.title"
        static let reviewSubtitle: LocalizedStringResource = "create_card.review.subtitle"
        static let descriptionLabel: LocalizedStringResource = "create_card.description.label"
        static let evidenceLabel: LocalizedStringResource = "create_card.evidence.label"
        static let noEvidence: LocalizedStringResource = "create_card.evidence.none"
        static let evidenceCount: LocalizedStringResource = "create_card.evidence.count"
        static let offlineNotice: LocalizedStringResource = "create_card.offline_notice"
        static let previous: LocalizedStringResource = "create_card.previous"
        static let save: LocalizedStringResource = "create_card.save"
        static let continueAction: LocalizedStringResource = "create_card.continue"
        static let stepClassify: LocalizedStringResource = "create_card.step.classify"
        static let stepLocation: LocalizedStringResource = "create_card.step.location"
        static let stepEvidence: LocalizedStringResource = "create_card.step.evidence"
        static let stepDetails: LocalizedStringResource = "create_card.step.details"
        static let stepReview: LocalizedStringResource = "create_card.step.review"
        static let selectType: LocalizedStringResource = "create_card.select.type"
        static let selectCondition: LocalizedStringResource = "create_card.select.condition"
        static let selectPreclassifier: LocalizedStringResource = "create_card.select.preclassifier"
        static let selectPriority: LocalizedStringResource = "create_card.select.priority"
        static let selectLevel: LocalizedStringResource = "create_card.select.level"
        static let selectDueDate: LocalizedStringResource = "create_card.select.due_date"
        static let selectOption: LocalizedStringResource = "create_card.select.option"
        static let levelRoot: LocalizedStringResource = "create_card.level.root"
        static let searchOptions: LocalizedStringResource = "create_card.search_options"
        static let useDate: LocalizedStringResource = "create_card.use_date"
        static let errorSite: LocalizedStringResource = "create_card.error.site"
        static let errorCatalogs: LocalizedStringResource = "create_card.error.catalogs"
        static let errorType: LocalizedStringResource = "create_card.error.type"
        static let errorCondition: LocalizedStringResource = "create_card.error.condition"
        static let errorPreclassifier: LocalizedStringResource = "create_card.error.preclassifier"
        static let errorPriority: LocalizedStringResource = "create_card.error.priority"
        static let errorLevel: LocalizedStringResource = "create_card.error.level"
        static let errorFinalLevel: LocalizedStringResource = "create_card.error.final_level"
        static let errorDescription: LocalizedStringResource = "create_card.error.description"
        static let errorDescriptionLength: LocalizedStringResource = "create_card.error.description_length"
        static let errorDueDate: LocalizedStringResource = "create_card.error.due_date"
        static let errorDueDateInvalid: LocalizedStringResource = "create_card.error.due_date_invalid"
        static let errorSelection: LocalizedStringResource = "create_card.error.selection"
        static let errorSave: LocalizedStringResource = "create_card.error.save"
        static let errorImageLimit: LocalizedStringResource = "create_card.error.image_limit"
        static let errorVideoLimit: LocalizedStringResource = "create_card.error.video_limit"
        static let errorAudioLimit: LocalizedStringResource = "create_card.error.audio_limit"
        static let errorVideoDuration: LocalizedStringResource = "create_card.error.video_duration"
        static let errorAudioDuration: LocalizedStringResource = "create_card.error.audio_duration"
        static let errorFileSize: LocalizedStringResource = "create_card.error.file_size"
        static let errorTotalEvidence: LocalizedStringResource = "create_card.error.total_evidence"
        static let errorInvalidMedia: LocalizedStringResource = "create_card.error.invalid_media"
        static let evidenceImportError: LocalizedStringResource = "create_card.error.evidence_import"
    }

    enum CardSync {
        static let inProgress: LocalizedStringResource = "card_sync.in_progress"
        static let progress: LocalizedStringResource = "card_sync.progress"
        static let preparing: LocalizedStringResource = "card_sync.preparing"
        static let successTitle: LocalizedStringResource = "card_sync.success.title"
        static let successBody: LocalizedStringResource = "card_sync.success.body"
        static let failureTitle: LocalizedStringResource = "card_sync.failure.title"
        static let failureBody: LocalizedStringResource = "card_sync.failure.body"
    }

    enum CardSolution {
        static let provisionalTitle: LocalizedStringResource = "card_solution.provisional.title"
        static let definitiveTitle: LocalizedStringResource = "card_solution.definitive.title"
        static let provisionalHeading: LocalizedStringResource = "card_solution.provisional.heading"
        static let definitiveHeading: LocalizedStringResource = "card_solution.definitive.heading"
        static let provisionalSubtitle: LocalizedStringResource = "card_solution.provisional.subtitle"
        static let definitiveSubtitle: LocalizedStringResource = "card_solution.definitive.subtitle"
        static let employee: LocalizedStringResource = "card_solution.employee.label"
        static let employeePlaceholder: LocalizedStringResource = "card_solution.employee.placeholder"
        static let employeeSearch: LocalizedStringResource = "card_solution.employee.search"
        static let employeeSheetTitle: LocalizedStringResource = "card_solution.employee.sheet_title"
        static let commentsPlaceholder: LocalizedStringResource = "card_solution.comments.placeholder"
        static let evidenceTitle: LocalizedStringResource = "card_solution.evidence.title"
        static let evidenceSubtitle: LocalizedStringResource = "card_solution.evidence.subtitle"
        static let offlineNotice: LocalizedStringResource = "card_solution.offline_notice"
        static let saveProvisional: LocalizedStringResource = "card_solution.provisional.save"
        static let saveDefinitive: LocalizedStringResource = "card_solution.definitive.save"
        static let errorNotFound: LocalizedStringResource = "card_solution.error.not_found"
        static let errorClosed: LocalizedStringResource = "card_solution.error.closed"
        static let errorApplied: LocalizedStringResource = "card_solution.error.applied"
        static let errorCardType: LocalizedStringResource = "card_solution.error.card_type"
        static let errorEmployee: LocalizedStringResource = "card_solution.error.employee"
        static let errorComments: LocalizedStringResource = "card_solution.error.comments"
        static let errorCommentsLength: LocalizedStringResource = "card_solution.error.comments_length"
        static let errorEvidenceProcessing: LocalizedStringResource = "card_solution.error.evidence_processing"
        static let errorSave: LocalizedStringResource = "card_solution.error.save"
    }

    enum CardDetail {
        static let title: LocalizedStringResource = "card_detail.title"
        static let notFound: LocalizedStringResource = "card_detail.not_found"
        static let informationTab: LocalizedStringResource = "card_detail.tab.information"
        static let evidenceTab: LocalizedStringResource = "card_detail.tab.evidence"
        static let generalInformation: LocalizedStringResource = "card_detail.general_information"
        static let site: LocalizedStringResource = "card_detail.site"
        static let location: LocalizedStringResource = "card_detail.location"
        static let type: LocalizedStringResource = "card_detail.type"
        static let classification: LocalizedStringResource = "card_detail.classification"
        static let preclassifier: LocalizedStringResource = "card_detail.preclassifier"
        static let priority: LocalizedStringResource = "card_detail.priority"
        static let created: LocalizedStringResource = "card_detail.created"
        static let due: LocalizedStringResource = "card_detail.due"
        static let createdBy: LocalizedStringResource = "card_detail.created_by"
        static let responsible: LocalizedStringResource = "card_detail.responsible"
        static let mechanic: LocalizedStringResource = "card_detail.mechanic"
        static let problemDescription: LocalizedStringResource = "card_detail.problem_description"
        static let provisionalSolution: LocalizedStringResource = "card_detail.provisional_solution"
        static let definitiveSolution: LocalizedStringResource = "card_detail.definitive_solution"
        static let managerClose: LocalizedStringResource = "card_detail.manager_close"
        static let noSolution: LocalizedStringResource = "card_detail.no_solution"
        static let date: LocalizedStringResource = "card_detail.date"
        static let user: LocalizedStringResource = "card_detail.user"
        static let comments: LocalizedStringResource = "card_detail.comments"
        static let deviceInformation: LocalizedStringResource = "card_detail.device_information"
        static let syncStatus: LocalizedStringResource = "card_detail.sync_status"
        static let app: LocalizedStringResource = "card_detail.app"
        static let syncError: LocalizedStringResource = "card_detail.sync_error"
        static let syncPending: LocalizedStringResource = "card_detail.sync.pending"
        static let syncing: LocalizedStringResource = "card_detail.sync.syncing"
        static let syncFailed: LocalizedStringResource = "card_detail.sync.failed"
        static let synced: LocalizedStringResource = "card_detail.sync.synced"
        static let creationEvidence: LocalizedStringResource = "card_detail.evidence.creation"
        static let provisionalEvidence: LocalizedStringResource = "card_detail.evidence.provisional"
        static let definitiveEvidence: LocalizedStringResource = "card_detail.evidence.definitive"
        static let noEvidence: LocalizedStringResource = "card_detail.evidence.none"
        static let images: LocalizedStringResource = "card_detail.evidence.images"
        static let videos: LocalizedStringResource = "card_detail.evidence.videos"
        static let audios: LocalizedStringResource = "card_detail.evidence.audios"
        static let retryEvidence: LocalizedStringResource = "card_detail.evidence.retry"
        static let imageDescription: LocalizedStringResource = "card_detail.evidence.image_description"
        static let playVideo: LocalizedStringResource = "card_detail.evidence.play_video"
        static let audioError: LocalizedStringResource = "card_detail.evidence.audio_error"
        static let evidenceUnavailable: LocalizedStringResource = "card_detail.evidence.unavailable"
    }

    enum Notes {
        static let title: LocalizedStringResource = "notes.title"
    }

    enum Settings {
        static let title: LocalizedStringResource = "settings.title"
        static let accountSection: LocalizedStringResource = "settings.account.section"
        static let applicationSection: LocalizedStringResource = "settings.application.section"
        static let information: LocalizedStringResource = "settings.information"
        static let informationDescription: LocalizedStringResource = "settings.information.description"
        static let permissions: LocalizedStringResource = "settings.permissions"
        static let permissionsDescription: LocalizedStringResource = "settings.permissions.description"
        static let permissionsPending: LocalizedStringResource = "settings.permissions.pending"
        static let mobileData: LocalizedStringResource = "settings.mobile_data"
        static let mobileDataDescription: LocalizedStringResource = "settings.mobile_data.description"
        static let version: LocalizedStringResource = "settings.version"
        static let logout: LocalizedStringResource = "settings.logout"
        static let accountInformationTitle: LocalizedStringResource = "settings.account_information.title"
        static let name: LocalizedStringResource = "settings.name"
        static let email: LocalizedStringResource = "settings.email"
        static let company: LocalizedStringResource = "settings.company"
        static let sites: LocalizedStringResource = "settings.sites"
        static let roles: LocalizedStringResource = "settings.roles"
        static let noSites: LocalizedStringResource = "settings.sites.empty"
        static let noRoles: LocalizedStringResource = "settings.roles.empty"
        static let close: LocalizedStringResource = "settings.close"
        static let logoutWarningTitle: LocalizedStringResource = "settings.logout.warning.title"
        static let logoutWarningBody: LocalizedStringResource = "settings.logout.warning.body"
        static let logoutError: LocalizedStringResource = "settings.logout.error"
    }

    enum CreateNote {
        static let title: LocalizedStringResource = "create_note.title"
    }
}
